### ISSUE TITLE
Where is the 1.0 iron element for this?

### ISSUE THREAD

**Issue by PabloJoan** [Polymer/core-scaffold#19]
why hasn't this been ported to polymer 1.0 iron elements?

**Comment by askibinski** [comment]
I've got exactly the same question. Is it work in progress? I know not every element has been converted yet, but there doesn't seem to be an overview which elements are "in progress".

I was looking for this to convert my app which uses core-scaffold and also core-header-panel, core-toolbar and core-item.

**Comment by askibinski** [comment]
After some digging around, I'm starting to believe the scaffold is deprecated and you should now use the iron-flex-layout element, see demo here: https://github.com/PolymerElements/iron-flex-layout/blob/master/demo/x-app.html

This is also mentioned somewhat in the migration guide, although core-scaffold is not mentioned there:
https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes

**Comment by addyosmani** [comment]
The scaffold hasn't been earmarked for porting just. See Polymer Starter Kit for a 1.0 scaffold or the app-layout-templates repo.

**Comment by arthurevans** [comment]
@askibinski `iron-flex-layout` is a set of stylesheets for doing flexbox layout. It replaces the layout attributes that were built into 0.5. It's not really related to `core-scaffold`.

@PabloJoan `core-scaffold` wasn't ported because it wasn't a very good element. It made for quick demos, but it wasn't very flexible and it didn't add much value over implementing your own version with a drawer panel and a couple of core-header-panels.

As Addy said, you can look at https://github.com/PolymerElements/app-layout-templates for a few simple scaffolds. You should be able to copy one of those templates to replace `core-scaffold` in your application.

If you want a more comprehensive starting point for an app, you can also look at https://github.com/PolymerElements/polymer-starter-kit.

**Comment by askibinski** [comment]
Thanks! Yes, app-layout-templates is exactly what I needed.
